[mountain]
name = "Mount Rainier"
height = 14411 # feet
height_unit = "FT"
latitude = 46.8523
longitude = -121.7603

[webcam]
name = "UW Red Square"
url = "https://www.washington.edu/cambots/camera1_l.jpg"
description = "UW Red Square webcam looking towards Mount Rainier"
latitude = 47.6553
longitude = -122.3035

[weather]
station_id = "KSEA"
description = "Seattle-Tacoma International Airport"
latitude = 47.4502
longitude = -122.3088
